spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

      # Optional but recommended
      enable-auto-commit: false

  profiles:
    active: default

server:
  port: 0

# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    net.devh.boot.grpc.server: INFO
    io.grpc: INFO
    com.company.billing: DEBUG

# ===============================
# ACTUATOR (Optional but recommended)
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always