spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/patientdb
    username: patientuser
    password: patientpass

  billing:
    grpc:
      host: billing-service
      port: 9090