spring:
  application:
    name: billing-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: billing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


  profiles:
    active: default

server:
  port: 0   # REST not exposed; gRPC only

# ===============================
# gRPC SERVER CONFIG
# ===============================
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}
    enable-reflection: true

# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    net.devh.boot.grpc.server: INFO
    io.grpc: INFO
    com.company.billing: DEBUG

# ===============================
# ACTUATOR (Optional but recommended)
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
